23andMe/Yamale

yamale/schema/schema.py
yamale/syntax/parser.py
yamale/syntax/tests/test_parser.py
yamale/tests/meta_test_fixtures/data_custom.yaml
yamale/tests/meta_test_fixtures/schema_custom.yaml
yamale/tests/test_meta_test.py
yamale/validators/__init__.py

Hi,
My name is Lionel and I'm working at a french firm called Polyconseil. I found your yamale library the other day, and it is really well made. Yamale could be very useful for our new YAML configuration architecture. I took the liberty to make this pull request to add a feature we need : the ability to add some custom validators to the default yamale validators. I used a pretty simple "date" validator for testing purpose, but we have other custom format we would like to validate, which can not be added to the default validators because they are not so standard. I hope I'll have the opportunity to make some other PRs in the near future to help and improve this nice tool.
Kind Regards

Adding custom validators support

---

yamale/util.py
yamale/validators/validators.py

Hi, since python 3.3 ABCs for containers were moved to their own module and will be removed from original in 3.8. This PR fixes it, can you please look into it?

Fix deprecation warnings

---

README.md
yamale/syntax/tests/test_parser.py
yamale/tests/fixtures/regex.yaml
yamale/tests/fixtures/regex_bad.yaml
yamale/tests/fixtures/regex_good.yaml
yamale/tests/fixtures/types.yaml
yamale/tests/fixtures/types_bad_data.yaml
yamale/tests/fixtures/types_good_data.yaml
yamale/tests/test_functional.py
yamale/validators/tests/test_validate.py
yamale/validators/validators.py

Hi, here's my stab at adding a regular expression validator. I would've created a feature request but one exists already at #40.
The default fail message was modified, because `'foo' is not a regex` didn't make any sense, but further customization of the fail message to something like `'foo' is not a User ID` may or may not be something you want.
I considered allowing regex flags to be passed to `re.compile()` by using the validator like `regex(r'pattern', [r'pattern2',] flags=re.IGNORECASE, name='eggs')`, but that looked like it would've required adding the `re` module (or at least the various flags it defines) to the allowed (very) short list of `safe_globals` in `syntax.parser`. So... never mind that. :relieved:
I also updated the README to document the validator and fix a minor …

Regular expression validator

---

yamale/schema/schema.py
yamale/tests/fixtures/issue_50.yaml
yamale/tests/fixtures/issue_50_good.yaml
yamale/tests/test_functional.py
yamale/util.py

When flattening keys, the previous separator was a period. This caused
issues when the key itself had a period in it. We changed the separator
to a string that should never appear in the wild.

Fix #50 by changing the separator.

---

yamale/schema/schema.py
yamale/tests/command_line_fixtures/required_keys_schema.yaml
yamale/tests/command_line_fixtures/yamls/required_keys_bad.yaml
yamale/tests/test_command_line.py

Oops, the separator was used in the error message output, replacing it
with a dot.

Fix error message output introduced in PR 58

---

yamale/validators/tests/test_validate.py

There were 3 deprecation warnings while running tests against Py36:
```
yamale/validators/tests/test_validate.py:40
/Users/dpasichnyi/ttam/Yamale/yamale/validators/tests/test_validate.py:40: DeprecationWarning: invalid escape sequence \s
v = val.Regex('[a-z0-9]{3,}s\s$', ignore_case=True)
yamale/validators/tests/test_validate.py:47
/Users/dpasichnyi/ttam/Yamale/yamale/validators/tests/test_validate.py:47: DeprecationWarning: invalid escape sequence \d
v = val.Regex('A.+\d$', ignore_case=False, multiline=True)
yamale/validators/tests/test_validate.py:51
/Users/dpasichnyi/ttam/Yamale/yamale/validators/tests/test_validate.py:51: DeprecationWarning: invalid escape sequence \.
v = val.Regex('.*^Ye.*s\.', ignore_case=True, multiline=True, dotall=True)
```
Fixed them by using raw string for …

Fix Deprecation Warning 'invalid escape sequence \*'

---

README.md
yamale/schema/schema.py
yamale/tests/fixtures/any.yaml
yamale/tests/fixtures/any_bad.yaml
yamale/tests/fixtures/any_good.yaml

Hi, this makes `any()` (without any arguments passed) to accept anything. This actually has the same effect by simply removing the key from the schema file. However, in my use case, I would like the users to see `key: any()` and knows that this key is optional rather than unavailable. Also, things get a bit different in strict mode, which would be helpful when one wants some key to present but does not care about its type. Thanks for reviewing!

Make any() accept anything

---

yamale/command_line.py
yamale/schema/validationresults.py
yamale/tests/test_command_line.py

The schema errors were short-circuiting the rest of the yaml validation
when processing several directories. Wrapping them in a Result object
and passing it along as we do with yaml validation results lets all
these results be processed at the end.

Construct Result object for schema errors

---

yamale/tests/fixtures/numeric_bool_coercion.yaml
yamale/tests/fixtures/numeric_bool_coercion_bad.yaml
yamale/tests/fixtures/numeric_bool_coercion_good.yaml
yamale/tests/test_functional.py
yamale/validators/validators.py

Adds a change to the Integer and Numeric validators such that they won't interpret boolean values (False, True) as valid, as well as tests outlining the expected behavior (and confirming that 0 and 1 are still accepted).
This is an issue caused by the origin of Bool in Python, as outlined in [PEP 285 -- Adding a bool type](https://www.python.org/dev/peps/pep-0285/):
> The bool type would be a straightforward subtype (in C) of the int type, and the values False and True would behave like 0 and 1 in most respects (for example, False==0 and True==1 would be true) except repr() and str().
For historical reasons, bool is a subtype of int in Python, but that is not the case in YAML (see e.g. https://yaml.org/type/bool.html). This can cause issues where Yamale validates a YAML document with a …

Prevent int and num validators from accepting bool values.

---

setup.py

Current version of Yamale removed support for Python2, however trying to install it on Python2.7 results in an error. Using the python_requires keyword allows user of a specific python version to get the latest compatible package instead.
The error:
```
pip2 install yamale --user --upgrade
Collecting yamale
Downloading https://files.pythonhosted.org/packages/1e/97/6734831a1316016ae16aa34a1875e77b9e8130f5b400c5bc96c24e56f79f/yamale-3.0.0.tar.gz
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/tmp/pip-build-5_sFTr/yamale/setup.py", line 4, in <module>
readme = open('README.md', encoding='utf-8').read()
TypeError: 'encoding' is an invalid keyword argument for this function …
```

Use python_requires in setup.py

---

README.md

The description of *any* as a *union* operator is easily missed, despite the presence of the word 'union': Add emphasis, more direct wording, and a clear, one-type example.

Update 'any' with another example and 'firmer' XOR wording.

---

README.md

In both *Install* and *Developers*, add a single paragraph highlighting additional software that may be required to run or text yamale, and providing direction for further reader research. Specific install instructions are not provided.

Add single-paragraph high-level version notes

---

README.md
yamale/schema/schema.py
yamale/tests/fixtures/subset.yaml
yamale/tests/fixtures/subset_bad.yaml
yamale/tests/fixtures/subset_bad2.yaml
yamale/tests/fixtures/subset_bad3.yaml
yamale/tests/fixtures/subset_empty.yaml
yamale/tests/fixtures/subset_empty_good.yaml
yamale/tests/fixtures/subset_good.yaml
yamale/tests/fixtures/subset_good2.yaml
yamale/tests/fixtures/subset_nodef.yaml
yamale/tests/test_functional.py
yamale/validators/validators.py

Similiar to the `any` validator, except it allows combining multiple types (instead of exactly one).
This is mostly useful for various `Include`s, thereby allowing some sort of conditional key-value pairs, such as the following. Granted this example is over-simplistic and can be resolved in other ways (such as explicitly specifying the mapping values), but this would apply to a recursive definition as well.
```yaml
my_types: union(include('type1'), include('type2'))
---
type1: map(str(), key=regex('^my_str(ing)?$', ignore_case=True))
---
type2: map(int(), key=regex('^my_int(eger)?$', ignore_case=True))
my_types:
my_string: foo
my_int: 3
my_types:
my_string: 3  # Not a string
my_int: foo  # Not an int
```

[Feature] Adds Subset validator

---

yamale/syntax/parser.py

When processing the schema, each line is run through Python's eval
function to make the validator available. A well constructed string
within the schema rules can execute system commands. This change limits
the string to those that begin with the known validators.

Limit the strings which can be eval'd

---

yamale/command_line.py

Hi,
Thanks for your great work!
There exists an issue I've encountered in several environments with printing "👍".
The problem is that we get "Validation failed!" trying to print "Validation success! 👍" which is both funny and incorrect.
The issue can be reproduced in ubuntu docker, but it is not limited to docker in my experience.
I prefer to keep the original message when possible, which dictates the `try ... except` approach in the PR.

Check for UnicodeEncodeError when printing the success message

---

.github/workflows/run-tests.yml
README.md
setup.py
tox.ini
yamale/syntax/parser.py

closes #234 
Note that this change is incompatible with Python `<3.8`, therefore I raised the `python_requires` lower bound accordingly

fix 3.12 deprecations

---

yamale/command_line.py
yamale/tests/test_command_line.py

Check that `schema_name` is a valid file before iterating over parent directories of `data_path` (the change is taken from [quite old PR](https://github.com/23andMe/Yamale/pull/192)).
Fix for https://github.com/23andMe/Yamale/issues/238 .
It is a breaking change in terms of behaviour (as [pointed out in the old PR](https://github.com/23andMe/Yamale/pull/192#issuecomment-1041892826)), because invocations like `yamale a/b/c.yaml --schema=x/y/z/schema.yaml` will now _first_ check `$PWD/x/y/z.yaml` file for being a schema _instead of_ starting from `$PWD/a/b/x/y/z/schema.yaml` and iterating over parents (`$PWD/a/x/y/z/schema`, `$PWD/x/y/z/schema`, etc). This changes the order in which schema files are used.
But, to be honest, I don't think this will cause many troubles, because the "fixed" …

fix(cli): check schema to be a valid path first

---

.github/workflows/run-tests.yml
.pre-commit-config.yaml
Makefile
README.md
ruff.toml
yamale/schema/schema.py
yamale/util.py
yamale/yamale_testcase.py

* Add ruff pre-commit hook and github action
* Fixes ruff lint errors. 
* Ignoring  `import *` and unused import warnings until there's more time to clean them up.

Add ruff gh action

---

yamale/schema/schema.py
yamale/tests/fixtures/any_undefined.yaml
yamale/tests/fixtures/any_undefined_schema.yaml
yamale/tests/test_functional.py

When an undefined `include()` is used inside any special validator that allows one of N types to be valid (e.g. `map()`, `any()`) -- no error is raised when the schema is valid despite the include being undefined and wrong.

#236 Hard fail on undefined includes

---

yamale/validators/validators.py

Fix SyntaxWarning:
```python
.../yamale/validators/validators.py:260: SyntaxWarning: invalid escape sequence '\d'
re.compile("^(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)(?:-(?P<prerelease>(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+(?P<buildmetadata>[0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$"),
```
To reproduce this error, you need to run Python with `-W error` or `export PYTHONWARNING=error`.
Error was there for semver only but I fixed typo for `mac()` as well

(fix)semver: SyntaxWarning: invalid escape sequence

---

.pre-commit-hooks.yaml

https://github.com/23andMe/Yamale/pull/258 added pre-commit support to Yamale, with `pass_filenames: false`, as only one path is supported at a time.
https://github.com/23andMe/Yamale/pull/251 added support for multiple paths.
Therefore now it is possible to use `pass_filenames: true` with pre-commit.
Sample run (filenames redacted):
```
% pre-commit run --all-files yamale-schema-verify --verbose
check yaml schema with Yamale............................................Passed
- hook id: yamale-schema-verify
- duration: 0.12s
Validating file1.yaml...
Validating file2.yaml...
Validating file3.yaml...
Validating file4.yaml...
Validation success! 👍
[...]
```

pre-commit: set pass_filenames to true
